"""
Composition Plan domain models.

A CompositionPlan represents the output of the CompositionPlannerEngine:
for each VisualIntent, the planner has selected a registered composition
and populated its data schema.

This is stored inside the script_visual_strategy artifact payload when
visual_mode == "composition".
"""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, model_validator


class CompositionBeat(BaseModel):
    """
    A single visual beat in the composition pipeline.

    Operates at the composition level (what storytelling pattern) rather than
    raw component level (which React component).
    """

    beat_id: str = Field(description="Sequential: beat_01, beat_02, ...")
    source_intent_id: str | None = Field(
        default=None,
        description="The exact VisualIntent.intent_id that produced this beat.",
    )
    source_idea_id: str | None = Field(
        default=None,
        description="The VisualIntentSequence.idea_id containing source_intent_id.",
    )
    source_visual_intent_artifact_id: str | None = Field(
        default=None,
        description="ArtifactStore ID of the persisted visual_intent source artifact.",
    )
    source_narration_excerpt: str | None = Field(
        default=None,
        description="Verbatim narration excerpt from the source VisualIntent used for this beat.",
    )
    composition_id: str = Field(
        description="A registered composition ID from CompositionRegistry. "
                    "e.g. 'metric_hero', 'calculation_story', 'broll_caption'."
    )
    variant: str | None = Field(
        default=None,
        description="Optional composition-specific variant. Must be in composition's allowed_variants.",
    )
    composition_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Data payload validated against the composition's Pydantic data model.",
    )
    asset_requirement: str = Field(
        default="none",
        description="'none' | 'optional_broll' | 'required_image'",
    )
    asset_query: str | None = Field(
        default=None,
        description="Stock media search query string if asset_requirement != 'none'.",
    )
    asset_queries: list[str] = Field(
        default_factory=list,
        description="Ordered candidate stock media search queries (1 to 3) generated by LLM.",
    )
    trigger_word: str | None = Field(
        default=None,
        description=(
            "A single verbatim word from the narration that triggers this beat. "
            "Same verbatim-matching rules as the legacy system."
        ),
    )
    visual_goal: str = Field(
        default="",
        description="Human-readable description of visual intent. Kept for debugging/logging only.",
    )
    relationship_type: str | None = Field(
        default=None,
        description="The semantic relationship_type from VisualIntent this beat was created for.",
    )
    used_fallback: bool = Field(
        default=False,
        description="True if this beat was created as a fallback rather than primary planner selection.",
    )
    fallback_reason: str | None = Field(
        default=None,
        description="Detailed reason if this beat was created via fallback (e.g. 'no_suitable_composition', 'validation_error').",
    )

    @model_validator(mode="after")
    def validate_source_reference(self) -> "CompositionBeat":
        source_fields = (
            self.source_intent_id,
            self.source_idea_id,
            self.source_visual_intent_artifact_id,
        )
        if any(value is not None for value in source_fields) and not all(
            isinstance(value, str) and value.strip() for value in source_fields
        ):
            raise ValueError(
                "CompositionBeat source reference requires source_intent_id, "
                "source_idea_id, and source_visual_intent_artifact_id together."
            )
        if self.asset_queries and not self.asset_query:
            self.asset_query = self.asset_queries[0]
        elif self.asset_query and not self.asset_queries:
            self.asset_queries = [self.asset_query]
        return self


class HookCompositionPlan(BaseModel):
    """Composition beats for opening hook."""

    hook_id: str = "hook"
    narration: str
    beats: list[CompositionBeat] = Field(default_factory=list)


class IdeaCompositionPlan(BaseModel):
    """Composition beats for one narrative idea."""

    idea_id: str
    narration: str
    beats: list[CompositionBeat] = Field(default_factory=list)


class FullCompositionPlan(BaseModel):
    """
    Complete composition plan for an entire video.

    This is attached to the script_visual_strategy artifact payload under
    the key "composition_plan" when visual_mode == "composition".
    """

    schema_version: str = "1"
    visual_mode: str = "composition"  # detector flag for VideoAssemblyHandler
    thesis: str
    hook_plan: HookCompositionPlan | None = None
    ideas: list[IdeaCompositionPlan] = Field(default_factory=list)
